### PR TITLE
the name resolver might not find getters

### LINKED ISSUE #222: if defined column value and property/field name are different, can't access from generated schema
My environment
+ Orma v2.3.3
+ Android Studio 2.0 preview 6
+ java version "1.8.0_73"

In the case of Java, define model below (TestDataJava.java)

```
@Table
public class TestDataJava {
    @Column(value = BaseColumns._ID)
    @PrimaryKey(autoincrement = true)
    public final long id;

    @Column(value = "count")
    public final int hogeCount;

    @Setter
    public TestDataJava(long id, int count){
        this.id = id;
        this.hogeCount = count;
    }
}
```

Then error happened at build.

```
/Users/gen0083/program/Sample/OrmaPractice/app/build/generated/source/kapt/debug/jp/gcreate/sample/ormapractice/TestDataJava_Schema.java
Error:(172, 33) エラー: シンボルを見つけられません
シンボル:   変数 count
場所: クラス TestDataJava_Schema
```

excerpt from TestDataJava_Schema

```
  @NonNull
  @Override
  public TestDataJava newModelFromCursor(@NonNull OrmaConnection conn, @NonNull Cursor cursor, int offset) {
    int hogeCount = cursor.getInt(offset + 0);
    long id = cursor.getLong(offset + 1);
    return new TestDataJava(id, count);
  }
```

---
In the case of Kotlin, define model below (TestData.kt),

```
@Table
class TestData {
    @Column(value = BaseColumns._ID)
    @PrimaryKey(autoincrement = true)
    val id: Long

    @Column(value = "count")
    val countHoge: Int

    constructor(@Setter(BaseColumns._ID) id: Long , @Setter("count") count: Int){
        this.id = id
        this.countHoge = count
    }
}
```

then error happend.
```
/Users/gen0083/program/Sample/OrmaPractice/app/build/generated/source/kapt/debug/jp/gcreate/sample/ormapractice/TestData_Schema.java
Error:(29, 19) エラー: countHogeはTestDataでprivateアクセスされます
Error:(35, 19) エラー: countHogeはTestDataでprivateアクセスされます
Error:(43, 19) エラー: idはTestDataでprivateアクセスされます
Error:(49, 19) エラー: idはTestDataでprivateアクセスされます
Error:(152, 20) エラー: countHogeはTestDataでprivateアクセスされます
Error:(154, 22) エラー: idはTestDataでprivateアクセスされます
Error:(161, 32) エラー: countHogeはTestDataでprivateアクセスされます
Error:(163, 34) エラー: idはTestDataでprivateアクセスされます
```

But i can access from other class.

```
val data = TestData(1,1)
val id = data.id // no error
```

If rename property to same value of annotation, then no error and TestData_Schema can access TestData properties.

```
@Table
class TestData {
    @Column(value = BaseColumns._ID)
    @PrimaryKey(autoincrement = true)
    val _id: Long

    @Column(value = "count")
    val count: Int

    constructor(@Setter(BaseColumns._ID) id: Long , @Setter("count") count: Int){
        this._id = id
        this.count = count
    }
}
```

### PR DESCRIPTION
**Pull request by gfx**
fix #222

### CODE REVIEW

File: processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java [hunk 1]
```diff
@@ -214,28 +214,28 @@ public boolean hasDirectAssociations() {
...
-                    setters.put(extractNameFromSetter(setter, executableElement), executableElement);
+                    getters.put(extractNameFromGetter(getter, methodElement), methodElement);
+                    setters.put(extractNameFromSetter(setter, methodElement), methodElement);
                 });
 
         columns.addAll(columnElements.stream()
                 .map((element) -> {
                     ColumnDefinition column = new ColumnDefinition(this, element);
-                    column.initGetterAndSetter(getters.get(column.columnName), setters.get(column.columnName));
+                    column.initGetterAndSetter(getters.get(column.name), setters.get(column.name));
```
Comment (gfx) [inline processor/src/main/java/com/github/gfx/android/orma/processor/model/SchemaDefinition.java]: The actual change is only here.
